spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/PatelPratik39/microservices_SpringBoot.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          search-paths: "section6/v2-springCloud/configserver/src/main/resources/config"
server:
  port: 8071


