spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
#          search-locations: "classpath:/config"
          search-locations: "file:////Users//pratikpatel//Documents//SpringBoot_Projects//microservices_SpringBoot//section6//v2-springCloud//configserver//src//main//resources//config"
server:
  port: 8071


