spring:
  config:
    activate:
      on-profile: prod
build:
  version: "1.0"

accounts:
  message: "Welcome to the Prats Banking App using Java Spring boot microservice - PROD APIs"
  contactDetails:
    name: "Mangoo MotiJi - Product Owner"
    email: "mangoo@email.com"
  callSupport:
    - (123)4567890
    - (999)8883434