
build:
  version: "1.0"
loans:
  message: "Welcome to the Prats Banking App using Java Spring boot microservice - PRODUCTION APIs"
  contactDetails:
    name: "Mangoo MotiJi - Product Owner"
    email: "mangoo@email.com"
  onCallSupport:
    - "(123)4567890"
    - "(999)8883434"
