services:
  network-deploy-service:
    networks:
      - prats39

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/



#      old

#  microservice-eureka-config:
#    extends:
#      service: microservice-configserver-config
#    depends_on:
#      eurekaserver:
#        condition: service_healthy
#    environment:
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

#services:
#  network-deploy-service:
#    networks:
#      - prats39
#
#  microservice-base-config:
#    extends:
#      service: network-deploy-service
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#
#  microservice-configserver-config:
#    extends:
#      service: microservice-base-config
#    depends_on:
#      eurekaserver:
#        condition: service_healthy
#    environment:
#      SPRING_PROFILES_ACTIVE: default
##      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
#      SPRING_CONFIG_IMPORT: configserver:http://configserver-ms:8071/
#
#  microservice-eureka-config:
#    extends:
#      service: microservice-configserver-config
#    depends_on:
#      eurekaserver:
#        condition: service_healthy
#    environment:
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver-ms:8070/eureka/



#services:
#  network-deploy-service:
#    networks:
#      - prats39
#
#  microservice-base-config:
#    extends:
#      service: network-deploy-service
#    deploy:
#      resources:
#        limits:
#          memory: 700m
#
#  microservice-configserver-config:
##    extends:
##      service: microservice-base-config
#    depends_on:
#      eurekaserver:
#        condition: service_healthy
#    environment:
#      SPRING_PROFILES_ACTIVE: default
#      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
#
#  microservice-eureka-config:
##    extends:
##      service: microservice-configserver-config
#    depends_on:
#      eurekaserver:
#        condition: service_healthy
#    environment:
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/