
build:
  version: "2.0"

loans:
  message: "Welcome to the Prats Banking App using Java Spring boot microservice - QA APIS"
  contactDetails:
    name: "Lallu Lal - QA Lead"
    email: "lallu@email.com"
  onCallSupport:
    - "(333)333-1234"
    - "(999)777-3434"
