#spring:
#  application:
#    name: "eurekaserver"
#  config:
#    import: "optional:configserver:http://localhost:8071/"
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  health:
#    liveness-state:
#      enabled: true
#    readiness-state:
#      enabled: true
#    endpoint:
#      health:
#        probes:
#          enabled: true
#  endpoint:
#    health:
#      probes:
#        enabled: true

server:
  port: 8761

spring:
  application:
    name: "eurekaserver"
  config:
    import: "optional:configserver:http://localhost:8071/"

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
    endpoint:
      health:
        probes:
          enabled: true
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework.cloud: DEBUG
    com.netflix: DEBUG
