services:
  accounts:
    image: "prats39/accounts:s4"
    container_name: accounts-microservice
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - prats39

  loans:
    image: "prats39/loans:s4"
    container_name: loans-microservice
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - prats39

  cards:
    image: "prats39/cards:s4"
    container_name: cards-microservice
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - prats39

networks:
  prats39:
    driver: "bridge"
