spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/PatelPratik39/microservices_SpringBoot.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          search-paths: "section8/"
#        git:
#          uri: "https://github.com/PatelPratik39/microservices_SpringBoot.git"
#          default-label: main
#          timeout: 5
#          clone-on-start: true
#          force-pull: true
#          search-paths: "section8/"
server:
  port: 8071

encrypt:
  key: "94AGXER3CU8ECNAKEKDC00L4F"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true