spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/PatelPratik39/microservices_SpringBoot.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          search-path: "section8/configserver/src/main/resources/config"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
    endpoint:
      health:
        probes:
          enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "94AGXER3CU8ECNAKEKDC00L4F"
server:
  port: 8071
