services:
  configserver:
    image: "prats39/configserver:s8"
    container_name: configserver-microService
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config
  # EurekaServer
  eurekaserver:
    image: "prats39/eurekaserver:s8"
    container_name: eurekaserver-microService
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  accounts:
    image: "prats39/accounts:s8"
    container_name: accounts-microService
    ports:
      - "8081:8081"
    networks:
      - prats39
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: "prats39/loans:s8"
    container_name: loans-microService
    ports:
      - "8091:8091"
    networks:
      - prats39
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: "prats39/cards:s8"
    container_name: cards-microService
    ports:
      - "9000:9000"
    networks:
      - prats39
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  prats39:
    driver: bridge
